### ISSUE TITLE
libcap-ng used by "/usr/sbin/mount.cifs" failed due to not having CAP_SETPCAP in capng_apply

### ISSUE THREAD

**Issue by Dan-Essin** [stevegrubb/libcap-ng#31] opened 2021-09-08 01:16 UTC
This service:
/etc/systemd/system/servers.service
[Unit]
Description=mount-servers systemd service.

[Service]
Type=simple
ExecStart=/bin/bash /usr/local/bin/mount-servers.sh

[Install]
WantedBy=multi-user.target

----------------------------------------

This script:
#!/bin/bash

mount -t cifs //192.168.1.200/Drive_E /mnt/server-e -o credentials=/root/.smbcredentials_server,nounix,dir_mode=0777,file_mode=0777
mount -t cifs //192.168.1.200/Drive_E/Dropbox /mnt/dropbox -o credentials=/root/.smbcredentials_server,nounix,dir_mode=0777,file_mode=0777
mount -t cifs //192.168.1.200/Drive_D /mnt/server-d -o credentials=/root/.smbcredentials_server,nounix,dir_mode=0777,file_mode=0777

------------------------------------------------------------

systemctl status servers               
× servers.service - mount-servers systemd service.
     Loaded: loaded (/usr/local/lib/systemd/system/servers.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-09-07 17:30:38 PDT; 44min ago
    Process: 13728 ExecStart=/bin/bash /usr/local/bin/mount-servers.sh (code=exited, status=32)
   Main PID: 13728 (code=exited, status=32)
        CPU: 15ms

Sep 07 17:30:38 fedora bash[13735]: mount error(16): Device or resource busy
Sep 07 17:30:38 fedora bash[13735]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Sep 07 17:30:38 fedora mount.cifs[13739]: libcap-ng used by "/usr/sbin/mount.cifs" failed due to not having CAP_SETPCAP in capng_apply
Sep 07 17:30:38 fedora bash[13738]: mount error(16): Device or resource busy
Sep 07 17:30:38 fedora bash[13738]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Sep 07 17:30:38 fedora bash[13740]: mount: /mnt/data: /dev/sdb1 already mounted on /mnt/backup.
Sep 07 17:30:38 fedora bash[13741]: mount: /mnt/backup: /dev/sdc1 already mounted on /mnt/data.
Sep 07 17:30:38 fedora bash[13742]: mount: /mnt/timeshift: /dev/sdd1 already mounted on /mnt/timeshift.
Sep 07 17:30:38 fedora systemd[1]: servers.service: Main process exited, code=exited, status=32/n/a
Sep 07 17:30:38 fedora systemd[1]: servers.service: Failed with result 'exit-code'.

Sep 07 17:30:38 fedora bash[13735]: mount error(16): Device or resource busy
Sep 07 17:30:38 fedora bash[13735]: Refer to the mount.cifs(8) manual page (e.g>
Sep 07 17:30:38 fedora mount.cifs[13739]: libcap-ng used by "/usr/sbin/mount.ci>
Sep 07 17:30:38 fedora bash[13738]: mount error(16): Device or resource busy
Sep 07 17:30:38 fedora bash[13738]: Refer to the mount.cifs(8) manual page (e.g>
Sep 07 17:30:38 fedora bash[13740]: mount: /mnt/data: /dev/sdb1 already mounted>
Sep 07 17:30:38 fedora bash[13741]: mount: /mnt/backup: /dev/sdc1 already mount>
Sep 07 17:30:38 fedora bash[13742]: mount: /mnt/timeshift: /dev/sdd1 already mo>
Sep 07 17:30:38 fedora systemd[1]: servers.service: Main process exited, code=e>
Sep 07 17:30:38 fedora systemd[1]: servers.service: Failed with result 'exit-co>
lines 1-17/17 (END)

**Comment by stevegrubb** [comment] 2021-09-08 12:42
This needs to be reported to mount.cifs developers. libcap-ng is reporting that the library has detected a misuse of the API.

**Comment by stevegrubb** [comment] 2021-09-28 16:32
If this has been reported against the cifs-utils software, we should close out this issue. Thanks.

**Comment by stevegrubb** [comment] 2021-12-18 19:15
Closing out this issue. The problem is with cifs-utils use of libcap-ng.

**Closed by stevegrubb** 2021-12-18 19:15 UTC
